### PR TITLE
upgrade to etcd/v3. 

### PR DESCRIPTION
**Pull request by tutumagi**
upgrade to etcd/v3. So we donnot need to replace grpc package to the lower version.

### CODE REVIEW

**Comment by cupen** [comment]
It seems that etcd-v3.5 is coming soon.
https://github.com/etcd-io/etcd/issues/12970

**Comment by tutumagi** [comment]
> It seems that etcd-v3.5 is coming soon.
> [etcd-io/etcd#12970](https://github.com/etcd-io/etcd/issues/12970)

Yep, we can upgrade to the official `3.5` version later.

**Comment by cupen** [comment]
@tutumagi etcdv3.5 is released. Let's go! :muscle:
https://github.com/etcd-io/etcd/releases/tag/v3.5.0

**Comment by tutumagi** [comment]
I will merge in next week.

**Comment by cupen** [comment]
> I will merge in next week.

@tutumagi  Hello,  your `pr` is picked here. #494  Thanks for your work.

/cc @rogeralsing

**Comment by tutumagi** [comment]
I have upgrade `etcd` to v3.5.0 on my fork branch. And what should I do next?

**Comment by cupen** [comment]
@tutumagi  Run the example  `_examples/cluster-restartgracefully` with etcd. 
It also use gpc-v1.26 in `go.mod`. Just remove it  like this `pr` https://github.com/AsynkronIT/protoactor-go/pull/494/commits/ad09928340f5f7fa42bbe9dd44d9c6c2328131e6

```
cd _examples/cluster-restartgracefully
make start-with-etcd
```
If every things is OK, you'll see some logs like:
```
2021/06/23 11:15:56 INFO  [Example]     requests grainId="client-1" status="start" 
2021/06/23 11:15:56 INFO  [Example]     requests grainId="client-8" status="start" 
2021/06/23 11:15:56 INFO  [Example]     requests grainId="client-2" status="start" 
2021/06/23 11:15:56 INFO  [Example]     requests grainId="client-5" status="start" 
2021/06/23 11:15:56 INFO  [Example]     requests grainId="client-7" status="start" 
2021/06/23 11:15:56 INFO  [Example]     requests grainId="client-9" status="start" 
2021/06/23 11:15:56 INFO  [Example]     requests grainId="client-4" status="start" 
2021/06/23 11:15:56 INFO  [Example]     requests grainId="client-0" status="start" 
2021/06/23 11:15:56 INFO  [Example]     requests grainId="client-6" status="start" 
2021/06/23 11:15:56 INFO  [Example]     requests grainId="client-3" status="start" 
2021/06/23 11:15:57 INFO  [Example]     requests grainId="client-8" status="end" loops=10000 take=1.337590244s 
2021/06/23 11:15:57 INFO  [Example]     requests grainId="client-1" status="end" loops=10000 take=1.337777042s 
2021/06/23 11:15:57 INFO  [Example]     requests grainId="client-9" status="end" loops=10000 take=1.432898883s 
2021/06/23 11:15:57 INFO  [Example]     requests grainId="client-5" status="end" loops=10000 take=1.432832689s 
2021/06/23 11:15:57 INFO  [Example]     requests grainId="client-0" status="end" loops=10000 take=1.436307804s 
2021/06/23 11:15:57 INFO  [Example]     requests grainId="client-4" status="end" loops=10000 take=1.513899654s 
2021/06/23 11:15:57 INFO  [Example]     requests grainId="client-2" status="end" loops=10000 take=1.515489662s 
2021/06/23 11:15:57 INFO  [Example]     requests grainId="client-7" status="end" loops=10000 take=1.51621749s 
2021/06/23 11:15:57 INFO  [Example]     requests grainId="client-3" status="end" loops=10000 take=1.516710336s 
2021/06/23 11:15:57 INFO  [Example]     requests grainId="client-6" status="end" loops=10000 take=1.517275484s 
2021/06/23 11:15:57 INFO  [Example]     end all. clients=10 total=100000 req/s=100000 take=1.517514248s 
2021/06/23 11:15:57 INFO  [Example]     countinue? (y/n)
```

Then renew all of the `go.mod` of  examples.
```
cd _examples
make go.mod
```

BTW: I'll close my `pr` #494 if you want to finish yours.

**Comment by tutumagi** [comment]
The merge done. And test `_examples/cluster-restartgracefully` works well.

**Comment by cupen** [comment]
@tutumagi   I think we can use `git rebase` and `git squash` for reduce redundant commits.
https://www.git-tower.com/learn/git/faq/git-squash/

btw: This `pr` is useful. I'll merge it into my personal branch.
cc @rogeralsing

**Comment by cupen** [comment]
@tutumagi Oh, a month has passed, sorry for delay. And  I hope you don't mind me talking a lot.

**Comment by rogeralsing** [comment]
What is the status on this one?

**Comment by cupen** [comment]
@rogeralsing 

> What is the status on this one?

Test OK on my branch. It's ready to merge.

**Review by cupen — APPROVED** [review]

**Pull request merged**
