### PR TITLE
Endpoint actor now doesn't crashloop

### PR DESCRIPTION
**Pull request by cupen**
Merged #369, no conflicts now.

### CODE REVIEW

**Comment by qjpcpu** [comment]
@cupen this commit has been reverted, so how to fix it now?

**Comment by cupen** [comment]
@qjpcpu Hi, it's not a critical bug. The recommended workaround is to use fixed port.
btw: I have tried to fix it several weeks ago, but no progress.  Maybe I will try again next month if I have spare time .

**Comment by qjpcpu** [comment]
> @qjpcpu Hi, it's not a critical bug. The recommended workaround is to use fixed port.
> btw: I have tried to fix it several weeks ago, but no progress. Maybe I will try again next month if I have spare time .

@cupen Our ip and port are dynamic, so it will change after pod restart. After serveral deployments, the cluster would generate many  error logs, so we would be grateful for your fix.

**Comment by qjpcpu** [comment]
@cupen hope you fix it soon 😁

**Comment by alexeyzimarev** [comment]
I'd recommend deploying proto clusters as stateful sets and use hostnames instead of ips.

**Pull request merged**
