### PR TITLE
Timer-based scheduler for delayed message delivery

### PR DESCRIPTION
**Pull request by stuartcarnie**

### CODE REVIEW

**Comment by rogeralsing** [comment]
Do we need to account for sending context status?
e.g. cancel sends that are scheduled after the sender context dies?

Maybe that would be weird, but at least worth discussing

**Comment by stuartcarnie** [comment]
@rogeralsing I left this in draft, as I did feel there were some things to discuss around a scheduler. It seems useful as-is; however, is this the right approach?

**Comment by rogeralsing** [comment]
For other readers: https://github.com/AsynkronIT/protoactor-go/issues/87

We do have this in .NET and you have used the same API here so I think we are good to go.

@AsynkronIT/developers thougths?

**Comment by stuartcarnie** [comment]
@rogeralsing I did based my implementation on the .NET one for that reason ;-)

**Comment by rogeralsing** [comment]
Merging this! :)

**Pull request merged**
